[package]
name = "my_bevy_platformer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.2", features = ["android"] }

[profile.release]
opt-level = "z"

[[bin]]
name = "my_bevy_platformer"
path = "src/main.rs"
